/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PagesSigninRouteImport } from './routes/_pages/signin'
import { Route as PagesUserIdRouteImport } from './routes/_pages/$userId'

const PagesSigninRoute = PagesSigninRouteImport.update({
  id: '/_pages/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesUserIdRoute = PagesUserIdRouteImport.update({
  id: '/_pages/$userId',
  path: '/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$userId': typeof PagesUserIdRoute
  '/signin': typeof PagesSigninRoute
}
export interface FileRoutesByTo {
  '/$userId': typeof PagesUserIdRoute
  '/signin': typeof PagesSigninRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pages/$userId': typeof PagesUserIdRoute
  '/_pages/signin': typeof PagesSigninRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$userId' | '/signin'
  fileRoutesByTo: FileRoutesByTo
  to: '/$userId' | '/signin'
  id: '__root__' | '/_pages/$userId' | '/_pages/signin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PagesUserIdRoute: typeof PagesUserIdRoute
  PagesSigninRoute: typeof PagesSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pages/signin': {
      id: '/_pages/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PagesSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pages/$userId': {
      id: '/_pages/$userId'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof PagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PagesUserIdRoute: PagesUserIdRoute,
  PagesSigninRoute: PagesSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
